# Generated by Django 5.1.15 on 2026-04-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homecare_customuser_homecare'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecare',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='homecare',
            name='endereco',
            field=models.TextField(blank=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='homecare',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='homecare_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='homecare',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone celular'),
        ),
        migrations.AddField(
            model_name='homecare',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone fixo'),
        ),
        migrations.AddField(
            model_name='homecare',
            name='whatsapp_celular',
            field=models.BooleanField(default=False, verbose_name='WhatsApp no celular'),
        ),
    ]
