# Generated by Django 5.1.15 on 2026-04-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('profissionais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('quadro_medico', models.TextField(blank=True, verbose_name='Quadro Médico')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plano_saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.planosaude', verbose_name='Plano de Saúde')),
                ('profissionais_autorizados', models.ManyToManyField(blank=True, related_name='pacientes_autorizados', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('recebe_mensagem', models.BooleanField(default=True, verbose_name='Recebe mensagem WhatsApp')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
    ]
