# Generated by Django 5.1.15 on 2026-04-08 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('profissionais', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_plantao', models.CharField(choices=[('1h', 'Plantão 1 hora'), ('3h', 'Plantão 3 horas'), ('6h', 'Plantão 6 horas'), ('12h', 'Plantão 12 horas'), ('procedimento', 'Procedimento Clínico')], default='procedimento', max_length=20, verbose_name='Tipo de Plantão')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Data e hora de início')),
                ('duracao_minutos', models.PositiveIntegerField(default=60, verbose_name='Duração (minutos)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='pacientes.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='catalogos.procedimentoclinico')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PedidoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_solicitacao', models.DateField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_exames', to='catalogos.exame')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_exames', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_exames', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Pedido de Exame',
                'verbose_name_plural': 'Pedidos de Exames',
            },
        ),
        migrations.CreateModel(
            name='ReceitaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Receita Médica')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='pacientes.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='profissionais.profissional')),
            ],
            options={
                'verbose_name': 'Receita Médica',
                'verbose_name_plural': 'Receitas Médicas',
            },
        ),
    ]
