# Generated by Django 5.1.15 on 2026-04-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homecare_customuser_homecare'),
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='homecare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos', to='accounts.homecare'),
        ),
        migrations.AddField(
            model_name='pedidoexame',
            name='homecare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_exames', to='accounts.homecare'),
        ),
        migrations.AddField(
            model_name='receitamedica',
            name='homecare',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='accounts.homecare'),
        ),
    ]
