# Generated by Django 5.1.15 on 2026-04-08 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_homecare_cnpj_homecare_endereco_homecare_logo_and_more'),
        ('agendamentos', '0002_agendamento_homecare_pedidoexame_homecare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='data_fim_repeticao',
            field=models.DateField(blank=True, help_text='Deixe em branco para repetição sem tempo determinado.', null=True, verbose_name='Data fim da repetição'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='repetir',
            field=models.BooleanField(default=False, verbose_name='Repetir plantão'),
        ),
        migrations.CreateModel(
            name='IntervaloRepeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Intervalo')),
                ('dias', models.PositiveIntegerField(default=1, verbose_name='Intervalo em dias')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('homecare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervalos_repeticao', to='accounts.homecare')),
            ],
            options={
                'verbose_name': 'Intervalo de Repetição',
                'verbose_name_plural': 'Intervalos de Repetição',
                'ordering': ['dias', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='intervalo_repeticao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.intervalorepeticao', verbose_name='Intervalo de repetição'),
        ),
    ]
