# Generated by Django 5.1.15 on 2026-04-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_agendamento_data_fim_repeticao_agendamento_repetir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='evolucao_plantao',
            field=models.TextField(blank=True, verbose_name='Evolução do plantão'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacao_administrador',
            field=models.TextField(blank=True, help_text='Lembrete ou comentário reservado para a equipe administrativa.', verbose_name='Observação para administradores'),
        ),
    ]
