# Generated by Django 5.1.15 on 2026-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Especialidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Especialidade',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Exame')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Medicamento')),
                ('principio_ativo', models.CharField(blank=True, max_length=200, verbose_name='Princípio Ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='OrgaoRegulador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Órgão Regulador')),
                ('sigla', models.CharField(blank=True, max_length=20, verbose_name='Sigla')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Órgão Regulador',
                'verbose_name_plural': 'Órgãos Reguladores',
            },
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Plano de Saúde')),
                ('operadora', models.CharField(blank=True, max_length=150, verbose_name='Operadora')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Plano de Saúde',
                'verbose_name_plural': 'Planos de Saúde',
            },
        ),
        migrations.CreateModel(
            name='ProcedimentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Procedimento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('duracao_padrao_minutos', models.PositiveIntegerField(default=60, verbose_name='Duração padrão (minutos)')),
            ],
            options={
                'verbose_name': 'Procedimento Clínico',
                'verbose_name_plural': 'Procedimentos Clínicos',
            },
        ),
    ]
