# Generated by Django 5.1.15 on 2026-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedencia_horas', models.PositiveIntegerField(default=2, verbose_name='Antecedência (horas)')),
                ('antecedencia_minutos', models.PositiveIntegerField(default=0, verbose_name='Antecedência (minutos)')),
                ('enviar_whatsapp', models.BooleanField(default=True, verbose_name='Enviar WhatsApp')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração de Sistema',
                'verbose_name_plural': 'Configurações de Sistema',
            },
        ),
    ]
